# Generated by Django 4.0.3 on 2022-04-14 16:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0011_poststatus_alter_category_options_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=tinymce.models.HTMLField(verbose_name='content'),
        ),
    ]
