# Generated by Django 4.0.3 on 2022-04-14 16:48

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0012_alter_post_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=tinymce.models.HTMLField(),
        ),
    ]
