# Generated by Django 4.0.3 on 2022-04-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0013_alter_post_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': '   Posts'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': '  Tags'},
        ),
    ]
