# Generated by Django 4.0.3 on 2022-04-19 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_poststatus'),
        ('blogpost', '0014_alter_post_options_alter_tag_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setting.poststatus'),
        ),
        migrations.DeleteModel(
            name='PostStatus',
        ),
    ]
