# Generated by Django 4.0.3 on 2023-02-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0017_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='medias/'),
        ),
    ]
