# Generated by Django 4.0.3 on 2022-04-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pb', 'Published'), ('Pd', 'Pending'), ('Dr', 'Draft')], max_length=50)),
            ],
        ),
    ]
