# Generated by Django 4.0.3 on 2022-04-19 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0016_alter_post_status'),
        ('setting', '0002_poststatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostStatus',
        ),
    ]
